[package]
name = "nuff_command_line"
version = { workspace = true }
publish = false
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
repository = { workspace = true }
license = { workspace = true }

[dependencies]
argfile = { workspace = true }

[lints]
workspace = true
