[package]
name = "nuff_python_trivia"
version = { workspace = true }
publish = false
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
repository = { workspace = true }
license = { workspace = true }

[lib]

[dependencies]
nuff_source_file = { workspace = true }
nuff_text_size = { workspace = true }

itertools = { workspace = true }
memchr = { workspace = true }
rustc-hash = { workspace = true }
unicode-ident = { workspace = true }
unicode-normalization = { workspace = true }

[lints]
workspace = true
