[build-system]
requires = ["maturin>=1.9.3,<2.0"]
build-backend = "maturin"

[project]
name = "nuff"
version = "0.3.0"
description = "Nordser's Python linter."
requires-python = ">=3.7"
license = "MIT"

[project.urls]
Repository = "https://github.com/NordserEng/nuff"

[tool.maturin]
bindings = "bin"
strip = true
