[package]
name = "nuff_db"
version = { workspace = true }
publish = false
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
repository = { workspace = true }
license = { workspace = true }

[dependencies]
nuff_annotate_snippets = { workspace = true }
nuff_cache = { workspace = true, optional = true }
nuff_diagnostics = { workspace = true }
nuff_memory_usage = { workspace = true }
nuff_notebook = { workspace = true }
nuff_python_ast = { workspace = true, features = ["get-size"] }
nuff_python_parser = { workspace = true }
nuff_python_trivia = { workspace = true }
nuff_source_file = { workspace = true, features = ["get-size"] }
nuff_text_size = { workspace = true }
nuff_static = { workspace = true }

anstyle = { workspace = true }
arc-swap = { workspace = true }
camino = { workspace = true }
compact_str = { workspace = true }
dashmap = { workspace = true }
dunce = { workspace = true }
filetime = { workspace = true }
get-size2 = { workspace = true }
ignore = { workspace = true, optional = true }
matchit = { workspace = true }
path-slash = { workspace = true }
pathdiff = { workspace = true }
quick-junit = { workspace = true, optional = true }
rustc-hash = { workspace = true }
salsa = { workspace = true }
same-file = { workspace = true, optional = true }
schemars = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }
similar = { workspace = true }
supports-hyperlinks = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, optional = true }
which = { workspace = true, optional = true }
zip = { workspace = true }

[target.'cfg(not(target_arch="wasm32"))'.dependencies]
etcetera = { workspace = true, optional = true }

[target.'cfg(target_arch="wasm32")'.dependencies]
web-time = { version = "1.1.0", default-features = false }

[dev-dependencies]
insta = { workspace = true, features = ["filters"] }
tempfile = { workspace = true }

[features]
cache = ["nuff_cache"]
junit = ["dep:quick-junit"]
os = ["ignore", "dep:etcetera", "dep:same-file", "dep:which"]
serde = [
    "camino/serde1",
    "dep:serde",
    "dep:serde_json",
    "nuff_diagnostics/serde",
]
# Exposes testing utilities.
testing = ["tracing-subscriber"]
