[package]
name = "nuff_index"
version = { workspace = true }
publish = false
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
repository = { workspace = true }
license = { workspace = true }

[lib]
doctest = false

[dependencies]
get-size2 = { workspace = true }
nuff_macros = { workspace = true }
salsa = { workspace = true, optional = true }

[dev-dependencies]
static_assertions = { workspace = true }

[lints]
workspace = true
