[package]
name = "nuff_static"
version = { workspace = true }
publish = false
edition = { workspace = true }
rust-version = { workspace = true }
repository = { workspace = true }
authors = { workspace = true }
license = { workspace = true }

[lib]
doctest = false
test = false

[dependencies]
nuff_macros = { workspace = true }

[lints]
workspace = true
